# Generated by Django 5.0.3 on 2024-03-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='course',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
