# Generated by Django 5.0.3 on 2024-03-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='course',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('MERN', 'MERN')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='course',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('MERN', 'MERN')], max_length=10),
        ),
    ]
